
public class Text {
    public final String EXIT = "Выход";
    public final String CHOICE = "Выбор";
    public final String BACK = "Назад";
    public final String OK = "ОК";
    public final String NEW_LANGUAGE = "Новый язык";
    public final String TIMING = "Синхронизация";
    public final String NEXT = "Продолжить";
    public final String SAVE = "Сохранить";
    public final String DELETE = "Удалить";
    public final String ORDERING_1 = "Сорт. по 1 записи";
    public final String ORDERING_2 = "Сорт. по 2 записи";
    public final String CANCEL = "Отмена";
    public final String START = "Пуск";
    public final String ADD_WORD = "Добавить новую пару";
    public final String SETTINGS = "Настройки";
    public final String MENU = "Меню";
    public final String TRUE = "Правильно";
    public final String FALSE = "Ошибка";
    public final String DICTIONARY = "Словарь";
    public final String LOGIN = "Логин:";
    public final String PASSWORD = "Пароль:";
    public final String URL = "url:";
    public final String LANGUAGE = "Язык:";
    public final String EMPTY_DICTIONARY = "Словарь пуст";
    public final String ENTER_THE_WORD_ORIGINALLY = "Введите слово на русском:";
    public final String ENTER_TRANSLATION = "Введите перевод:";
    public final String KNOWLEDGE = "Оцените то, как вы знаете это слово:";
    public final String DONT_KNOW = "Не знаю";
    public final String BAD = "Плохо";
    public final String NORMALLY = "Нормально";
    public final String GOOD = "Хорошо";
    public final String VERY_GOOD = "Отлично";
    public final String NUMBER_OF_WORDS = "Количество слов в игре:";
    public final String TIMING_COMPLETE = "Синхронизация завершена";
    public final String PLEASE_WAIT = "Подождите, идет";
    public final String CHANGE = "Изменить";
}
